### PR TITLE
Feature/testing setup

### PR DESCRIPTION
**Pull request by frankmariette**
## Changes made
-  Added Karma and Jasmine for testing purposes
-  Modified Gulp to run the Karma server and be setup for TDD. 
## Why is this needed?

In order to write unit tests and allow for TDD style development, a testing suite is required. After research, Karma and Jasmine seemed to be a better fit for building as the suite runs quickly as opposed to Facebook's Jest which is designed for testing their React applications. The setup also allows us the flexibility to test anything else as well. This will not work for e2e testing but that will be setup later on after the initial site is up and running.

### CODE REVIEW

**Comment by ryan-endacott** [comment]
I didn't look over the code much, but the idea sounds good to me.  Jasmine looks nice too.  

Would you mind adding to the readme how to run the tests?

**Comment by ryan-endacott** [comment]
Also, this is just a nitpick, but would you mind rebasing the "gitignore" and "merge conflicts" commits into one of the previous ones?

**Comment by frankmariette** [comment]
Done for both issues

**Comment by ryan-endacott** [comment]
Great, thanks! Looks good to me. Anyone else have thoughts?

**Comment by ghost** [comment]
Looks good but not quite sure what all these libraries do for us and how we will take advantage of them. If you could elaborate on this that would be great. :D

**Comment by frankmariette** [comment]
Karma - Is a test runner. This runs our unit tests for us. http://karma-runner.github.io/0.12/index.html
Jasmine - Testing suite. Lets us write unit tests in javascript. This library works well with React and is the base testing suite used by FaceBook for React. 
Browserify - Builds our JS distribution as well as allows us to use NPM modules in the browser. Node modules use the CommonJS standard and so it makes things easy to include. On top of this it provides the require() function for use in client based code for dependencies.

**Comment by ryan-endacott** [comment]
:+1: Thanks for the explanations.

**Comment by frankmariette** [comment]
No problem, going to merge this in unless anyone has an issue with it.

**Pull request merged**
